// <auto-generated />
using System;
using Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260118123708_seed_customer")]
    partial class seed_customer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("pk_customer");

                    b.ToTable("customer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(2396),
                            Email = "customer1@example.com",
                            Name = "Customer 1",
                            Phone = "10000000001"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3522),
                            Email = "customer2@example.com",
                            Name = "Customer 2",
                            Phone = "10000000002"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3530),
                            Email = "customer3@example.com",
                            Name = "Customer 3",
                            Phone = "10000000003"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3557),
                            Email = "customer4@example.com",
                            Name = "Customer 4",
                            Phone = "10000000004"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3559),
                            Email = "customer5@example.com",
                            Name = "Customer 5",
                            Phone = "10000000005"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3566),
                            Email = "customer6@example.com",
                            Name = "Customer 6",
                            Phone = "10000000006"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3568),
                            Email = "customer7@example.com",
                            Name = "Customer 7",
                            Phone = "10000000007"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3570),
                            Email = "customer8@example.com",
                            Name = "Customer 8",
                            Phone = "10000000008"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3571),
                            Email = "customer9@example.com",
                            Name = "Customer 9",
                            Phone = "10000000009"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3574),
                            Email = "customer10@example.com",
                            Name = "Customer 10",
                            Phone = "10000000010"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3576),
                            Email = "customer11@example.com",
                            Name = "Customer 11",
                            Phone = "10000000011"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3577),
                            Email = "customer12@example.com",
                            Name = "Customer 12",
                            Phone = "10000000012"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3579),
                            Email = "customer13@example.com",
                            Name = "Customer 13",
                            Phone = "10000000013"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3584),
                            Email = "customer14@example.com",
                            Name = "Customer 14",
                            Phone = "10000000014"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3586),
                            Email = "customer15@example.com",
                            Name = "Customer 15",
                            Phone = "10000000015"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3588),
                            Email = "customer16@example.com",
                            Name = "Customer 16",
                            Phone = "10000000016"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3589),
                            Email = "customer17@example.com",
                            Name = "Customer 17",
                            Phone = "10000000017"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3592),
                            Email = "customer18@example.com",
                            Name = "Customer 18",
                            Phone = "10000000018"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3594),
                            Email = "customer19@example.com",
                            Name = "Customer 19",
                            Phone = "10000000019"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3595),
                            Email = "customer20@example.com",
                            Name = "Customer 20",
                            Phone = "10000000020"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3597),
                            Email = "customer21@example.com",
                            Name = "Customer 21",
                            Phone = "10000000021"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3598),
                            Email = "customer22@example.com",
                            Name = "Customer 22",
                            Phone = "10000000022"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3600),
                            Email = "customer23@example.com",
                            Name = "Customer 23",
                            Phone = "10000000023"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3601),
                            Email = "customer24@example.com",
                            Name = "Customer 24",
                            Phone = "10000000024"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3603),
                            Email = "customer25@example.com",
                            Name = "Customer 25",
                            Phone = "10000000025"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3604),
                            Email = "customer26@example.com",
                            Name = "Customer 26",
                            Phone = "10000000026"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3606),
                            Email = "customer27@example.com",
                            Name = "Customer 27",
                            Phone = "10000000027"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3608),
                            Email = "customer28@example.com",
                            Name = "Customer 28",
                            Phone = "10000000028"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3609),
                            Email = "customer29@example.com",
                            Name = "Customer 29",
                            Phone = "10000000029"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3616),
                            Email = "customer30@example.com",
                            Name = "Customer 30",
                            Phone = "10000000030"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3618),
                            Email = "customer31@example.com",
                            Name = "Customer 31",
                            Phone = "10000000031"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3619),
                            Email = "customer32@example.com",
                            Name = "Customer 32",
                            Phone = "10000000032"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3621),
                            Email = "customer33@example.com",
                            Name = "Customer 33",
                            Phone = "10000000033"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3664),
                            Email = "customer34@example.com",
                            Name = "Customer 34",
                            Phone = "10000000034"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3666),
                            Email = "customer35@example.com",
                            Name = "Customer 35",
                            Phone = "10000000035"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3668),
                            Email = "customer36@example.com",
                            Name = "Customer 36",
                            Phone = "10000000036"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3669),
                            Email = "customer37@example.com",
                            Name = "Customer 37",
                            Phone = "10000000037"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3671),
                            Email = "customer38@example.com",
                            Name = "Customer 38",
                            Phone = "10000000038"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3672),
                            Email = "customer39@example.com",
                            Name = "Customer 39",
                            Phone = "10000000039"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3674),
                            Email = "customer40@example.com",
                            Name = "Customer 40",
                            Phone = "10000000040"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3676),
                            Email = "customer41@example.com",
                            Name = "Customer 41",
                            Phone = "10000000041"
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3677),
                            Email = "customer42@example.com",
                            Name = "Customer 42",
                            Phone = "10000000042"
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3679),
                            Email = "customer43@example.com",
                            Name = "Customer 43",
                            Phone = "10000000043"
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3680),
                            Email = "customer44@example.com",
                            Name = "Customer 44",
                            Phone = "10000000044"
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3682),
                            Email = "customer45@example.com",
                            Name = "Customer 45",
                            Phone = "10000000045"
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3683),
                            Email = "customer46@example.com",
                            Name = "Customer 46",
                            Phone = "10000000046"
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3685),
                            Email = "customer47@example.com",
                            Name = "Customer 47",
                            Phone = "10000000047"
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3687),
                            Email = "customer48@example.com",
                            Name = "Customer 48",
                            Phone = "10000000048"
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3688),
                            Email = "customer49@example.com",
                            Name = "Customer 49",
                            Phone = "10000000049"
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3690),
                            Email = "customer50@example.com",
                            Name = "Customer 50",
                            Phone = "10000000050"
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 372, DateTimeKind.Utc).AddTicks(3691),
                            Email = "customer51@example.com",
                            Name = "Customer 51",
                            Phone = "10000000051"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresIn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_in");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_time");

                    b.Property<string>("ConfirmedBy")
                        .HasColumnType("text")
                        .HasColumnName("confirmed_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<decimal?>("DepositAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("deposit_amount");

                    b.Property<decimal?>("DepositAmountPaid")
                        .HasColumnType("numeric")
                        .HasColumnName("deposit_amount_paid");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_guests");

                    b.Property<bool?>("RequiresDeposit")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_deposit");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reservation_date");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer")
                        .HasColumnName("restaurant_id");

                    b.Property<string>("SpecialRequests")
                        .HasColumnType("text")
                        .HasColumnName("special_requests");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("transactionId")
                        .HasColumnType("text")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_reservation");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_reservation_customer_id");

                    b.HasIndex("Guid")
                        .IsUnique()
                        .HasDatabaseName("ix_reservation_guid");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("ix_reservation_restaurant_id");

                    b.ToTable("reservation", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReservationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_reservation_status");

                    b.ToTable("reservation_status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 378, DateTimeKind.Utc).AddTicks(8796),
                            Name = "PENDING"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 378, DateTimeKind.Utc).AddTicks(9128),
                            Name = "CONFIRMED"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 378, DateTimeKind.Utc).AddTicks(9128),
                            Name = "CHECKED IN"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 378, DateTimeKind.Utc).AddTicks(9129),
                            Name = "REVIEW"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 378, DateTimeKind.Utc).AddTicks(9130),
                            Name = "COMPLETED"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 378, DateTimeKind.Utc).AddTicks(9130),
                            Name = "CANCELLED"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 378, DateTimeKind.Utc).AddTicks(9131),
                            Name = "NO SHOW"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_restaurant");

                    b.ToTable("restaurant", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 18, 12, 37, 7, 379, DateTimeKind.Utc).AddTicks(4383),
                            Name = "Standart Restaurant"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RestaurantReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("integer")
                        .HasColumnName("restaurant_id");

                    b.HasKey("Id")
                        .HasName("pk_restaurant_review");

                    b.HasIndex("RestaurantId")
                        .HasDatabaseName("ix_restaurant_review_restaurant_id");

                    b.ToTable("restaurant_review", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Reservation", b =>
                {
                    b.HasOne("Domain.Entities.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_customer_customer_id");

                    b.HasOne("Domain.Entities.Restaurant", "Restaurant")
                        .WithMany("Reservations")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_restaurant_restaurant_id");

                    b.Navigation("Customer");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Domain.Entities.RestaurantReview", b =>
                {
                    b.HasOne("Domain.Entities.Restaurant", "Restaurant")
                        .WithMany("Reviews")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_restaurant_review_restaurant_restaurant_id");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Domain.Entities.Customer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Domain.Entities.Restaurant", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
